version: "2.3"


services:
  mvn:
    build:
      context: ./
      args:
        - UID=1000

  ear-build:
    extends: mvn
    volumes:
      - ./home:/home/developer
    working_dir: /home/developer
    command:
      - ./build.sh
